spring:
  data:
    mongodb:
      host: your mongo db host
      port: 35732
      username: your username
      password: your password
      database: your db
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 115MB
          
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 36000000

file:
  upload-dir: ./upload/images

imagepath: /upload/images/


logging:
  level:
    org.springframework.web: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

UserController:
  signin: Login
  signup: Mendaftar User Baru
  me: Mengembalikan Current User

CartController:
  index: Menampilkan Keranjang Current User
  add: Menambahkan Produk ke Keranjang
  remove: Menghapus Produk dari Keranjang

OrderController:
  create: Membuat Order
  index: Menampilkan Order dari Current User
  seller: Menampilkan Order dari Current User sebagai Seller
  accept: Menerima Pesanan
  delivered: Merubah status pesanan ke delivered

ProductController:
  index: Menampilkan daftar Produk
  show: Menampilkan Produk Berdasarkan ID
  store: Menambahkan Produk

ProfileController:
  me: Menampilkan Current Profile
  edit: Update data Profile

CategoryController:
  index: Menampilkan Semua Category

ReviewController:
  create: Menambahkan Review

